import type { MenuEntry } from '@twnr/shared';

/**
 * Hardcoded menu registry. 
 *
 * If you add a new key binding for a server-driven menu, add it here.
 * Client-only sub-modes (computer, attack, droneEncounter, port pre-dock,
 * starbaseHardware) live in their per-menu files.
 * 
 * The duplication here exists so the shared
    help_menu routine (common-routines.ts) can enumerate the
    available commands when the user hits `?`. Keep both lists in
    sync when adding/removing computer commands.
 */
export const MENU_REGISTRY: MenuEntry[] = [
    {
        name: 'sector',
        label: 'Sector',
        parentMenu: null,
        commands: [
            {
                command: 'display_sector',
                keyPattern: '<enter>',
                label: 'Re-display sector',
                targetMenu: null,
                sortOrder: 5,
            },
            {
                command: 'move',
                keyPattern: '<number>',
                label: 'Move to sector #',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'move_previous',
                keyPattern: '<',
                label: 'Previous sector',
                targetMenu: null,
                sortOrder: 15,
            },
            {
                command: 'move_menu',
                keyPattern: 'm',
                label: 'Move to adjacent sector',
                targetMenu: null,
                sortOrder: 25,
            },
            {
                command: 'port_menu',
                keyPattern: 'p',
                label: 'Port',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'player_info',
                keyPattern: 'i',
                label: 'Player info',
                targetMenu: null,
                sortOrder: 40,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 50,
            },
            {
                command: 'attack_menu',
                keyPattern: 'a',
                label: 'Attack',
                targetMenu: null,
                sortOrder: 60,
            },
            {
                command: 'computer_menu',
                keyPattern: 'c',
                label: 'Computer',
                targetMenu: null,
                sortOrder: 70,
            },
            {
                command: 'deploy_drones_info',
                keyPattern: 'd',
                label: 'Deploy drones',
                targetMenu: null,
                sortOrder: 80,
            },
            {
                command: 'list_deployed_drones',
                keyPattern: 'g',
                label: 'Deployed Drones',
                targetMenu: null,
                sortOrder: 85,
            },
            {
                command: 'deploy_mines_menu',
                keyPattern: 'n',
                label: 'Deploy mines',
                targetMenu: null,
                sortOrder: 86,
            },
            {
                command: 'list_deployed_mines',
                keyPattern: 'e',
                label: 'Deployed Mines',
                targetMenu: null,
                sortOrder: 87,
            },
            {
                command: 'mine_disruptor_menu',
                keyPattern: 'r',
                label: 'Mine Disruptor',
                targetMenu: null,
                sortOrder: 88,
            },
            {
                command: 'jettison_menu',
                keyPattern: 'j',
                label: 'Jettison cargo',
                targetMenu: null,
                sortOrder: 90,
            },
            {
                command: 'use_terraform_device',
                keyPattern: 'u',
                label: 'Terraform',
                targetMenu: null,
                sortOrder: 95,
            },
            { command: 'land', keyPattern: 'l', label: 'Land', targetMenu: null, sortOrder: 100 },
            {
                command: 'starbase_info',
                keyPattern: 'v',
                label: 'Starbase info',
                targetMenu: null,
                sortOrder: 105,
            },
            {
                command: 'transporter_pad',
                keyPattern: 'x',
                label: 'Transporter Pad',
                targetMenu: null,
                sortOrder: 108,
            },
            {
                command: 'clan_menu',
                keyPattern: 't',
                label: 'Clan',
                targetMenu: 'clan',
                sortOrder: 109,
            },
            {
                command: 'quit_game',
                keyPattern: 'q',
                label: 'Quit',
                targetMenu: null,
                sortOrder: 110,
            },
            {
                command: 'players_online',
                keyPattern: '#',
                label: 'Players online',
                targetMenu: null,
                sortOrder: 120,
            },
        ],
    },
    {
        name: 'port',
        label: 'Port',
        parentMenu: 'sector',
        commands: [],
    },
    {
        name: 'computer',
        label: 'Computer',
        parentMenu: 'sector',
        commands: [
            {
                command: 'known_universe',
                keyPattern: 'k',
                label: 'Known universe map',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'trader_list',
                keyPattern: 'l',
                label: 'Trader list',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'ship_catalog',
                keyPattern: 'c',
                label: 'Ship catalog',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'planet_specs',
                keyPattern: 'j',
                label: 'Planet specs',
                targetMenu: null,
                sortOrder: 40,
            },
            {
                command: 'current_ship_specs',
                keyPattern: ';',
                label: 'Current ship specs',
                targetMenu: null,
                sortOrder: 50,
            },
            {
                command: 'list_deployed_drones',
                keyPattern: 'd',
                label: 'List deployed drones',
                targetMenu: null,
                sortOrder: 60,
            },
            {
                command: 'hyperspace_jump',
                keyPattern: 'h',
                label: 'Hyperspace jump',
                targetMenu: null,
                sortOrder: 70,
            },
            {
                command: 'list_planets',
                keyPattern: 'y',
                label: 'List planets',
                targetMenu: null,
                sortOrder: 80,
            },
            {
                command: 'track_seeker_mines',
                keyPattern: 'm',
                label: 'Track seeker mines',
                targetMenu: null,
                sortOrder: 90,
            },
            {
                command: 'change_ship_ownership',
                keyPattern: 'o',
                label: 'Change ship ownership',
                targetMenu: null,
                sortOrder: 92,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 95,
            },
            {
                command: 'back',
                keyPattern: 'q',
                label: 'Back to sector',
                targetMenu: null,
                sortOrder: 100,
            },
        ],
    },
    {
        name: 'class0',
        label: 'Class 0 Port',
        parentMenu: 'port',
        commands: [
            {
                command: 'choose_holds',
                keyPattern: 'a',
                label: 'Cargo holds',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'choose_drones',
                keyPattern: 'b',
                label: 'Drones',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'choose_shields',
                keyPattern: 'c',
                label: 'Shield Points',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'leave_port',
                keyPattern: 'q',
                label: 'Quit, nevermind',
                targetMenu: null,
                sortOrder: 40,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 50,
            },
        ],
    },
    {
        name: 'planet',
        label: 'Planet',
        parentMenu: 'sector',
        commands: [
            {
                command: 'planet_display',
                keyPattern: '<enter>',
                label: 'Re-display planet',
                targetMenu: null,
                sortOrder: 5,
            },
            {
                command: 'take_colonists',
                keyPattern: 't',
                label: 'Take colonists',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'leave_colonists',
                keyPattern: 'l',
                label: 'Leave colonists',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'take_commodity',
                keyPattern: 'g',
                label: 'Get commodity',
                targetMenu: null,
                sortOrder: 22,
            },
            {
                command: 'leave_commodity',
                keyPattern: 'p',
                label: 'Put commodity',
                targetMenu: null,
                sortOrder: 24,
            },
            {
                command: 'planet_display',
                keyPattern: 'd',
                label: 'Planet Info',
                targetMenu: null,
                sortOrder: 25,
            },
            {
                command: 'destroy_planet',
                keyPattern: 'z',
                label: 'Destroy Planet',
                targetMenu: null,
                sortOrder: 35,
            },
            {
                command: 'claim_planet',
                keyPattern: 'o',
                label: 'Claim Planet',
                targetMenu: null,
                sortOrder: 37,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 40,
            },
            {
                command: 'leave_planet',
                keyPattern: 'q',
                label: 'Leave Planet',
                targetMenu: null,
                sortOrder: 50,
            },
        ],
    },
    {
        name: 'planetEarth',
        label: 'Earth',
        parentMenu: 'sector',
        commands: [],
    },
    {
        name: 'starbase',
        label: 'Starbase',
        parentMenu: 'sector',
        commands: [
            {
                command: 'shipyards_menu',
                keyPattern: 's',
                label: 'Shipyards',
                targetMenu: 'shipyards',
                sortOrder: 10,
            },
            {
                command: 'hardware_store',
                keyPattern: 'h',
                label: 'Hardware Store',
                targetMenu: 'starbaseHardware',
                sortOrder: 20,
            },
            {
                command: 'list_deployed_drones',
                keyPattern: 'd',
                label: 'Deployed Drones',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 35,
            },
            {
                command: 'back',
                keyPattern: 'q',
                label: 'Leave Starbase',
                targetMenu: null,
                sortOrder: 40,
            },
        ],
    },
    {
        name: 'starbaseHardware',
        label: 'Hardware Store',
        parentMenu: 'starbase',
        commands: [],
    },
    {
        name: 'clan',
        label: 'Clan',
        parentMenu: 'sector',
        commands: [
            {
                command: 'clan_display_list',
                keyPattern: 'd',
                label: 'Display Clans',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'clan_display_info',
                keyPattern: 'i',
                label: 'Your Clan Info',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'clan_make',
                keyPattern: 'm',
                label: 'Make a New Clan',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'clan_join',
                keyPattern: 'j',
                label: 'Join a Clan',
                targetMenu: null,
                sortOrder: 40,
            },
            {
                command: 'clan_leave',
                keyPattern: 'x',
                label: 'Leave Your Clan',
                targetMenu: null,
                sortOrder: 50,
            },
            {
                command: 'clan_transfer_credits',
                keyPattern: 'c',
                label: 'Credit Transfer',
                targetMenu: null,
                sortOrder: 60,
            },
            {
                command: 'clan_transfer_drones',
                keyPattern: 'f',
                label: 'Drone (Fighter) Transfer',
                targetMenu: null,
                sortOrder: 61,
            },
            {
                command: 'clan_transfer_mines',
                keyPattern: 'h',
                label: 'Mine Transfer',
                targetMenu: null,
                sortOrder: 62,
            },
            {
                command: 'clan_transfer_shields',
                keyPattern: 's',
                label: 'Shield Transfer',
                targetMenu: null,
                sortOrder: 63,
            },
            {
                command: 'clan_memo',
                keyPattern: 't',
                label: 'Send Clan Memo',
                targetMenu: null,
                sortOrder: 70,
            },
            {
                command: 'clan_set_password',
                keyPattern: 'p',
                label: 'Clan Security (password)',
                targetMenu: null,
                sortOrder: 80,
            },
            {
                command: 'clan_drop_member',
                keyPattern: 'r',
                label: 'Drop Clan Member',
                targetMenu: null,
                sortOrder: 85,
            },
            {
                command: 'clan_help',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 95,
            },
            {
                command: 'back',
                keyPattern: 'q',
                label: 'Exit Clan Menu',
                targetMenu: null,
                sortOrder: 100,
            },
        ],
    },
    {
        name: 'shipyards',
        label: 'Shipyards',
        parentMenu: 'starbase',
        commands: [
            {
                command: 'buy_ship',
                keyPattern: 'b',
                label: 'Buy a new ship',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'examine_ships',
                keyPattern: 'e',
                label: 'Examine ship specs',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'shipyards_equipment',
                keyPattern: 'p',
                label: 'Purchase equipment',
                targetMenu: 'shipyardsClass0',
                sortOrder: 30,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 35,
            },
            {
                command: 'back',
                keyPattern: 'q',
                label: 'Back',
                targetMenu: 'starbase',
                sortOrder: 40,
            },
        ],
    },
    {
        name: 'shipyardsClass0',
        label: 'Shipyards Equipment',
        parentMenu: 'shipyards',
        commands: [
            {
                command: 'choose_holds',
                keyPattern: 'a',
                label: 'Cargo holds',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'choose_drones',
                keyPattern: 'b',
                label: 'Drones',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'choose_shields',
                keyPattern: 'c',
                label: 'Shield Points',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'back',
                keyPattern: 'q',
                label: 'Back',
                targetMenu: 'shipyards',
                sortOrder: 40,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 50,
            },
        ],
    },
];
