import { Menu, type MenuEntry, type MenuCommandEntry, type MenuName } from '@twnr/shared';
import type { GameContext } from './types.js';
import { showSectorPrompt } from './display.js';
import { showAttackPrompt, showDroneEncounterPrompt } from './display-combat.js';
import { showComputerPrompt, showBaseComputerPrompt } from './display-computer.js';

/** Common command list for both the sector Computer menu and the Base
 *  Computer menu. The `back` label differs (back-to-sector vs back-to-base)
 *  so it's parameterized. */
function computerCommandsWithBack(backLabel: string): MenuCommandEntry[] {
    return [
        { command: 'known_universe',         keyPattern: 'k', label: 'Known universe map',  targetMenu: null, sortOrder: 10 },
        { command: 'trader_list',            keyPattern: 'l', label: 'Trader list',          targetMenu: null, sortOrder: 20 },
        { command: 'ship_catalog',           keyPattern: 'c', label: 'Ship catalog',         targetMenu: null, sortOrder: 30 },
        { command: 'planet_specs',           keyPattern: 'j', label: 'Planet specs',         targetMenu: null, sortOrder: 40 },
        { command: 'current_ship_specs',     keyPattern: ';', label: 'Current ship specs',   targetMenu: null, sortOrder: 50 },
        { command: 'list_deployed_drones',   keyPattern: 'd', label: 'Show deployed drones', targetMenu: null, sortOrder: 60 },
        { command: 'list_deployed_mines',    keyPattern: 'n', label: 'Show deployed mines',  targetMenu: null, sortOrder: 65 },
        { command: 'read_mail',              keyPattern: 'm', label: 'Read your mail',       targetMenu: null, sortOrder: 66 },
        { command: 'hail',                   keyPattern: '=', label: 'Hailing frequencies',  targetMenu: null, sortOrder: 67 },
        { command: 'hyperspace_jump',        keyPattern: 'h', label: 'Hyperspace jump',      targetMenu: null, sortOrder: 70 },
        { command: 'list_planets',           keyPattern: 'y', label: 'List planets',         targetMenu: null, sortOrder: 80 },
        { command: 'track_seeker_mines',     keyPattern: 't', label: 'Track limpet mines',   targetMenu: null, sortOrder: 90 },
        { command: 'change_ship_ownership',  keyPattern: 'o', label: 'Change ship ownership',targetMenu: null, sortOrder: 92 },
        { command: 'active_ship_scan',       keyPattern: 'z', label: 'Active ship scan',     targetMenu: null, sortOrder: 93 },
        { command: 'help_menu',              keyPattern: '?', label: 'Help',                 targetMenu: null, sortOrder: 95 },
        { command: 'back',                   keyPattern: 'q', label: backLabel,              targetMenu: null, sortOrder: 100 },
    ];
}
import { showClanPrompt } from './display-clan.js';
import { showPlanetMenuOptions, showEarthPrompt, showBasePrompt } from './display-planet.js';
import { showClass0Menu } from './display-port.js';
import {
    showStarbaseMenu,
    showHardwarePrompt,
    showShipyardsMenu,
    showShipyardsClass0Menu,
} from './display-starbase.js';

/**
 * Single source of truth for both the data side of menus (key bindings,
 * labels) and the behavior side (prompt renderer). Each menu's commands
 * dispatch through the routine registry in `routines/`; the registry below
 * tells the client what keys are valid where and what to render at the
 * prompt for each menu.
 */
export const MENU_REGISTRY: MenuEntry[] = [
    {
        name: 'sector',
        label: 'Sector',
        parentMenu: null,
        commands: [
            {
                command: 'display_sector',
                keyPattern: '<enter>',
                label: 'Re-display sector',
                targetMenu: null,
                sortOrder: 5,
            },
            {
                command: 'move',
                keyPattern: '<number>',
                label: 'Move to sector #',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'move_previous',
                keyPattern: '<',
                label: 'Previous sector',
                targetMenu: null,
                sortOrder: 15,
            },
            {
                command: 'move_menu',
                keyPattern: 'm',
                label: 'Move to adjacent sector',
                targetMenu: null,
                sortOrder: 25,
            },
            {
                command: 'port_menu',
                keyPattern: 'p',
                label: 'Port',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'player_info',
                keyPattern: 'i',
                label: 'Player info',
                targetMenu: null,
                sortOrder: 40,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 50,
            },
            {
                command: 'attack_menu',
                keyPattern: 'a',
                label: 'Attack',
                targetMenu: null,
                sortOrder: 60,
            },
            {
                command: 'computer_menu',
                keyPattern: 'c',
                label: 'Computer',
                targetMenu: null,
                sortOrder: 70,
            },
            {
                command: 'deploy_drones_info',
                keyPattern: 'd',
                label: 'Deploy drones',
                targetMenu: null,
                sortOrder: 80,
            },
            {
                command: 'handle_mines_menu',
                keyPattern: 'h',
                label: 'Handle mines',
                targetMenu: null,
                sortOrder: 86,
            },
            {
                command: 'mine_disruptor_menu',
                keyPattern: 'm',
                label: 'Mine Disruptor',
                targetMenu: null,
                sortOrder: 88,
            },
            {
                command: 'release_beacon',
                keyPattern: 'r',
                label: 'Release Beacon',
                targetMenu: null,
                sortOrder: 89,
            },
            {
                command: 'long_range_scan',
                keyPattern: 's',
                label: 'Long Range Scan',
                targetMenu: null,
                sortOrder: 91,
            },
            {
                command: 'tow_spacecraft',
                keyPattern: 'w',
                label: 'Tow Spacecraft',
                targetMenu: null,
                sortOrder: 92,
            },
            {
                command: 'jettison_menu',
                keyPattern: 'j',
                label: 'Jettison cargo',
                targetMenu: null,
                sortOrder: 90,
            },
            {
                command: 'use_terraform_device',
                keyPattern: 'u',
                label: 'Terraform',
                targetMenu: null,
                sortOrder: 95,
            },
            { command: 'land', keyPattern: 'l', label: 'Land', targetMenu: null, sortOrder: 100 },
            {
                command: 'order_starport',
                keyPattern: 'o',
                label: 'Order/upgrade StarPort',
                targetMenu: null,
                sortOrder: 102,
            },
            {
                command: 'starbase_info',
                keyPattern: 'v',
                label: 'Starbase info',
                targetMenu: null,
                sortOrder: 105,
            },
            {
                command: 'transporter_pad',
                keyPattern: 'x',
                label: 'Transporter Pad',
                targetMenu: null,
                sortOrder: 108,
            },
            {
                command: 'clan_menu',
                keyPattern: 't',
                label: 'Clan',
                targetMenu: 'clan',
                sortOrder: 109,
            },
            {
                command: 'quit_game',
                keyPattern: 'q',
                label: 'Quit',
                targetMenu: null,
                sortOrder: 110,
            },
            {
                command: 'players_online',
                keyPattern: '#',
                label: 'Players online',
                targetMenu: null,
                sortOrder: 120,
            },
        ],
    },
    {
        name: 'port',
        label: 'Port',
        parentMenu: 'sector',
        commands: [],
    },
    {
        name: 'computer',
        label: 'Computer',
        parentMenu: 'sector',
        commands: computerCommandsWithBack('Back to sector'),
    },
    {
        name: 'class0',
        label: 'Class 0 Port',
        parentMenu: 'port',
        commands: [
            {
                command: 'choose_holds',
                keyPattern: 'a',
                label: 'Cargo holds',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'choose_drones',
                keyPattern: 'b',
                label: 'Drones',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'choose_shields',
                keyPattern: 'c',
                label: 'Shield Points',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'leave_port',
                keyPattern: 'q',
                label: 'Quit, nevermind',
                targetMenu: null,
                sortOrder: 40,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 50,
            },
        ],
    },
    {
        name: 'planet',
        label: 'Planet',
        parentMenu: 'sector',
        commands: [
            {
                command: 'planet_display',
                keyPattern: '<enter>',
                label: 'Re-display planet',
                targetMenu: null,
                sortOrder: 5,
            },
            {
                command: 'load_unload_colonists',
                keyPattern: 's',
                label: 'Load/Unload Colonists',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'take_leave_product',
                keyPattern: 't',
                label: 'Take or Leave Product',
                targetMenu: null,
                sortOrder: 12,
            },
            {
                command: 'change_population',
                keyPattern: 'p',
                label: 'Change Population Lvls',
                targetMenu: null,
                sortOrder: 14,
            },
            {
                command: 'planet_display',
                keyPattern: 'd',
                label: 'Display Planet',
                targetMenu: null,
                sortOrder: 25,
            },
            {
                command: 'destroy_planet',
                keyPattern: 'z',
                label: 'Destroy Planet',
                targetMenu: null,
                sortOrder: 35,
            },
            {
                command: 'claim_planet',
                keyPattern: 'o',
                label: 'Claim Planet',
                targetMenu: null,
                sortOrder: 37,
            },
            {
                command: 'planetary_defense_bastion',
                keyPattern: 'b',
                label: 'Planetary Defense Bastion',
                targetMenu: 'base',
                sortOrder: 38,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 40,
            },
            {
                command: 'leave_planet',
                keyPattern: 'q',
                label: 'Leave Planet',
                targetMenu: null,
                sortOrder: 50,
            },
        ],
    },
    {
        name: 'base',
        label: 'Base',
        parentMenu: 'planet',
        commands: [
            {
                command: 'base_computer',
                keyPattern: 'c',
                label: 'Base Computer',
                targetMenu: 'baseComputer',
                sortOrder: 10,
            },
            {
                command: 'scan_sector',
                keyPattern: 's',
                label: 'Scan the Sector',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 40,
            },
            {
                command: 'exit_base',
                keyPattern: 'q',
                label: 'Exit to Planet Surface',
                targetMenu: null,
                sortOrder: 50,
            },
        ],
    },
    {
        name: 'baseComputer',
        label: 'Base Computer',
        parentMenu: 'base',
        commands: computerCommandsWithBack('Back to base'),
    },
    {
        name: 'planetEarth',
        label: 'Earth',
        parentMenu: 'sector',
        commands: [
            {
                command: 'take_from_earth',
                keyPattern: 't',
                label: 'Take colonists',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'leave_on_earth',
                keyPattern: 'l',
                label: 'Leave colonists',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'back',
                keyPattern: 'q',
                label: 'Leave Planet',
                targetMenu: null,
                sortOrder: 40,
            },
        ],
    },
    {
        name: 'attack',
        label: 'Attack',
        parentMenu: 'sector',
        commands: [
            {
                command: 'select_target',
                keyPattern: '<number>',
                label: 'Select target #',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'back',
                keyPattern: 'q',
                label: 'Cancel attack',
                targetMenu: null,
                sortOrder: 20,
            },
        ],
    },
    {
        name: 'droneEncounter',
        label: 'Drone Encounter',
        parentMenu: 'sector',
        commands: [
            {
                command: 'attack_sector_drones',
                keyPattern: 'a',
                label: 'Attack',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'retreat_from_drones',
                keyPattern: 'r',
                label: 'Retreat',
                targetMenu: null,
                sortOrder: 20,
            },
        ],
    },
    {
        name: 'starbase',
        label: 'Starbase',
        parentMenu: 'sector',
        commands: [
            {
                command: 'shipyards_menu',
                keyPattern: 's',
                label: 'Shipyards',
                targetMenu: 'shipyards',
                sortOrder: 10,
            },
            {
                command: 'hardware_store',
                keyPattern: 'h',
                label: 'Hardware Store',
                targetMenu: 'starbaseHardware',
                sortOrder: 20,
            },
            {
                command: 'list_deployed_drones',
                keyPattern: 'd',
                label: 'Deployed Drones',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 35,
            },
            {
                command: 'back',
                keyPattern: 'q',
                label: 'Leave Starbase',
                targetMenu: null,
                sortOrder: 40,
            },
        ],
    },
    {
        name: 'starbaseHardware',
        label: 'Hardware Store',
        parentMenu: 'starbase',
        commands: [
            { command: 'buy_terraform_device', keyPattern: 't', label: 'Terraform Device', targetMenu: null, sortOrder: 10 },
            { command: 'buy_planet_buster', keyPattern: 'b', label: 'Planet Buster', targetMenu: null, sortOrder: 20 },
            { command: 'buy_buoy', keyPattern: 'u', label: 'Marker Beacon', targetMenu: null, sortOrder: 30 },
            { command: 'buy_mine_disruptor', keyPattern: 'd', label: 'Mine Disruptor', targetMenu: null, sortOrder: 40 },
            { command: 'buy_cloaking_device', keyPattern: 'k', label: 'Cloaking Device', targetMenu: null, sortOrder: 50 },
            { command: 'buy_corbomite', keyPattern: 'c', label: 'Corbomite', targetMenu: null, sortOrder: 60 },
            { command: 'buy_photon_torpedo', keyPattern: 'h', label: 'Photon Torpedo', targetMenu: null, sortOrder: 70 },
            { command: 'buy_recon_drone', keyPattern: 'r', label: 'Recon Drone', targetMenu: null, sortOrder: 80 },
            { command: 'buy_mines_menu', keyPattern: 'm', label: 'Mines (proximity/limpet)', targetMenu: null, sortOrder: 90 },
            { command: 'buy_hyperspace_1', keyPattern: '1', label: 'Hyperspace I', targetMenu: null, sortOrder: 100 },
            { command: 'buy_hyperspace_2', keyPattern: '2', label: 'Hyperspace II', targetMenu: null, sortOrder: 110 },
            { command: 'buy_visual_scanner', keyPattern: 'v', label: 'Visual Scanner', targetMenu: null, sortOrder: 120 },
            { command: 'buy_planet_scanner', keyPattern: 'n', label: 'Planet Scanner', targetMenu: null, sortOrder: 130 },
            { command: 'help_menu', keyPattern: '?', label: 'Help', targetMenu: null, sortOrder: 140 },
            { command: 'back', keyPattern: 'q', label: 'Back to Starbase', targetMenu: null, sortOrder: 150 },
        ],
    },
    {
        name: 'clan',
        label: 'Clan',
        parentMenu: 'sector',
        commands: [
            {
                command: 'clan_display_list',
                keyPattern: 'd',
                label: 'Display Clans',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'clan_display_info',
                keyPattern: 'i',
                label: 'Your Clan Info',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'clan_make',
                keyPattern: 'm',
                label: 'Make a New Clan',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'clan_join',
                keyPattern: 'j',
                label: 'Join a Clan',
                targetMenu: null,
                sortOrder: 40,
            },
            {
                command: 'clan_leave',
                keyPattern: 'x',
                label: 'Leave Your Clan',
                targetMenu: null,
                sortOrder: 50,
            },
            {
                command: 'clan_transfer_credits',
                keyPattern: 'c',
                label: 'Credit Transfer',
                targetMenu: null,
                sortOrder: 60,
            },
            {
                command: 'clan_transfer_drones',
                keyPattern: 'f',
                label: 'Drone (Fighter) Transfer',
                targetMenu: null,
                sortOrder: 61,
            },
            {
                command: 'clan_transfer_mines',
                keyPattern: 'h',
                label: 'Mine Transfer',
                targetMenu: null,
                sortOrder: 62,
            },
            {
                command: 'clan_transfer_shields',
                keyPattern: 's',
                label: 'Shield Transfer',
                targetMenu: null,
                sortOrder: 63,
            },
            {
                command: 'clan_memo',
                keyPattern: 't',
                label: 'Send Clan Memo',
                targetMenu: null,
                sortOrder: 70,
            },
            {
                command: 'clan_set_password',
                keyPattern: 'p',
                label: 'Clan Security (password)',
                targetMenu: null,
                sortOrder: 80,
            },
            {
                command: 'clan_drop_member',
                keyPattern: 'r',
                label: 'Drop Clan Member',
                targetMenu: null,
                sortOrder: 85,
            },
            {
                command: 'clan_help',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 95,
            },
            {
                command: 'back',
                keyPattern: 'q',
                label: 'Exit Clan Menu',
                targetMenu: null,
                sortOrder: 100,
            },
        ],
    },
    {
        name: 'shipyards',
        label: 'Shipyards',
        parentMenu: 'starbase',
        commands: [
            {
                command: 'buy_ship',
                keyPattern: 'b',
                label: 'Buy a new ship',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'examine_ships',
                keyPattern: 'e',
                label: 'Examine ship specs',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'shipyards_equipment',
                keyPattern: 'p',
                label: 'Purchase equipment',
                targetMenu: 'shipyardsClass0',
                sortOrder: 30,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 35,
            },
            {
                command: 'back',
                keyPattern: 'q',
                label: 'Back',
                targetMenu: 'starbase',
                sortOrder: 40,
            },
        ],
    },
    {
        name: 'shipyardsClass0',
        label: 'Shipyards Equipment',
        parentMenu: 'shipyards',
        commands: [
            {
                command: 'choose_holds',
                keyPattern: 'a',
                label: 'Cargo holds',
                targetMenu: null,
                sortOrder: 10,
            },
            {
                command: 'choose_drones',
                keyPattern: 'b',
                label: 'Drones',
                targetMenu: null,
                sortOrder: 20,
            },
            {
                command: 'choose_shields',
                keyPattern: 'c',
                label: 'Shield Points',
                targetMenu: null,
                sortOrder: 30,
            },
            {
                command: 'back',
                keyPattern: 'q',
                label: 'Back',
                targetMenu: 'shipyards',
                sortOrder: 40,
            },
            {
                command: 'help_menu',
                keyPattern: '?',
                label: 'Help',
                targetMenu: null,
                sortOrder: 50,
            },
        ],
    },
];

/** Prompt-renderer bindings for each menu. Menus not listed here (e.g.
 *  `port`) render nothing by themselves — useful for transitional states
 *  whose visible UI is driven by server responses. */
export const MENU_PROMPTS: Partial<Record<MenuName, (ctx: GameContext) => void>> = {
    [Menu.Sector]: showSectorPrompt,
    [Menu.Attack]: showAttackPrompt,
    [Menu.Computer]: showComputerPrompt,
    [Menu.Clan]: showClanPrompt,
    [Menu.Planet]: showPlanetMenuOptions,
    [Menu.PlanetEarth]: showEarthPrompt,
    [Menu.DroneEncounter]: showDroneEncounterPrompt,
    [Menu.Class0]: (ctx) => void showClass0Menu(ctx),
    [Menu.Starbase]: showStarbaseMenu,
    [Menu.StarbaseHardware]: showHardwarePrompt,
    [Menu.Shipyards]: showShipyardsMenu,
    [Menu.ShipyardsClass0]: showShipyardsClass0Menu,
    [Menu.Base]: showBasePrompt,
    [Menu.BaseComputer]: showBaseComputerPrompt,
};
